import { getQuizzes } from '@/actions/server/quiz';
import QuizPage from './QuizPlayer';

// meta data for SEO
export const metadata = {
  title: "Quiz",
  description: "Generated by create next app",
};

const Quiz = async () => {

    const quiz = await getQuizzes();

    return (
        <div>
            <QuizPage quiz={quiz}></QuizPage>
        </div>
    );
}
export default Quiz;