import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import NextAutProvider from "@/provider/NextAutProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CS Campus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAutProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header>
            <Navbar />
          </header>

          <main className="min-h-screen">
            {children}
          </main>

          <footer>
            <Footer />
          </footer>
        </body>
      </html>
    </NextAutProvider>
  );
}
